### ISSUE TITLE
Additions for the species invalidation list

### ISSUE THREAD

**Issue by bmesuere** [unipept/make-database#12]
During database construction, we heuristically invalidate some species. These species should be added:
- [Bacterium](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=1869227): [178K proteins](https://www.uniprot.org/uniprot/?query=organism%3A%22bacterium+%5B1869227%5D%22&sort=score) 
- [Proteobacteria bacterium](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=1977087): [164K proteins](https://www.uniprot.org/uniprot/?query=taxonomy:1977087)
- [Ruminococcaceae bacterium](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?lvl=0&id=1898205): [131K proteins](https://www.uniprot.org/uniprot/?query=taxonomy:1898205)

Check that everything between bacteria and bacterium is also negative in the lineage.

**Comment by bmesuere** [comment]
After doing some more research, it seems that NCBI changed their naming strategy. If they had in unknown species with a known genus, they used to call that "unidentified <genusname>" which we invalidated. It now seems that they use "<genusname> bacterium" which we don't invalidate. This potentially affects [up to 23 million proteins](https://www.uniprot.org/uniprot/?query=taxonomy%3Abacterium&sort=score).

An invalidation rule could be do invalidate if rank is species and name ends in a space followed by "bacterium".

**Comment by ninewise** [comment]
I found [631 currently valid taxa](https://github.com/unipept/make-database/files/4700681/nieuw-invalids-a.txt) would this rule would invalidate. There are also [314 additional currently valid taxa](https://github.com/unipept/make-database/files/4700696/nieuw-invalids-b.txt)
 which match ' bacterium.*' at species level, should these be invalidated, too? They look invalid to me, at least.

**Comment by pdawyndt** [comment]
None of these are valid taxon names.
